### ISSUE TITLE
[BUGFIX][FRONT&BACK]게시글

### ISSUE THREAD

**Issue by KangSanLee24** [KangSanLee24/hunsu-project#285]
# Issue: 🐵BUGFIX

## 🎈Description

2. 게시글 작성시 해시태그가 필수인 상태이다. - 500 에러 - 서버인듯 -> 프론트 백 둘 다 문제였다.
3. 게시글 삭제 안된다. -> 잘 된다. 왜?

## 🎹Progress

- [x] 프론트 게시글 생성 함수
- [x] 프론트 게시글 수정 함수
- [x] 백엔드 게시글 생성 API
- [x] 백엔드 게시글 수정 API

**Comment by KangSanLee24** [comment]
```
query: START TRANSACTION
query: INSERT INTO `posts`(`id`, `user_id`, `title`, `category`, `content`, `hashtags`, `created_at`, `updated_at`) VALUES (DEFAULT, ?, ?, ?, ?, ?, DEFAULT, DEFAULT) -- PARAMETERS: [1,"게시글 생성 해쉬태그 없이 가능한가?","FASHION","ㅍㅁㄴㅇㄹ",null]
query failed: INSERT INTO `posts`(`id`, `user_id`, `title`, `category`, `content`, `hashtags`, `created_at`, `updated_at`) VALUES (DEFAULT, ?, ?, ?, ?, ?, DEFAULT, 
DEFAULT) -- PARAMETERS: [1,"게시글 생성 해쉬태그 없이 가능한가?","FASHION","ㅍㅁㄴ
ㅇㄹ",null]
error: Error: Column 'hashtags' cannot be null
query: ROLLBACK
[Nest] 10164  - 2024. 08. 19. 오후 12:33:11   ERROR [ExceptionsHandler] Column 'hashtags' cannot be null
```

DB 저장할 때, hashtag가 null값이면 저장이 안됨. 

1. 해시태그를 nullable하게 설정.
2. 해시태그가 없을 경우 빈배열로 저장하여 null이 안되게 처리 - 이걸로함

```
    // 2. 해시태그 유효성 체크 (입력된 경우에만 수행)
    let hashtags: string[] = [];
    if (hashtagsString) {
      const isValidHashtags = this.validateHashtags(hashtagsString);
      if (!isValidHashtags) {
        throw new BadRequestException('해시태그를 양식에 맞게 입력해주세요.'); // 유효하지 않은 해시태그에 대한 예외 처리
      }
      hashtags = hashtagsString.split(',').map((tag) => tag.trim()); // 해시태그를 배열로 변환
    }
 ```

**Comment by KangSanLee24** [comment]
```0|hunsu-project  | [Nest] 12626  - 08/19/2024, 3:43:00 AM   ERROR [ExceptionsHandler] Cannot read properties of null (reading 'nickname')
0|hunsu-project  | TypeError: Cannot read properties of null (reading 'nickname')
0|hunsu-project  |     at /home/ubuntu/hunsu-project/src/post/post.service.ts:198:31
0|hunsu-project  |     at Array.map (<anonymous>)
0|hunsu-project  |     at PostService.findAll (/home/ubuntu/hunsu-project/src/post/post.service.ts:195:22)
0|hunsu-project  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
0|hunsu-project  |     at PostController.findAll (/home/ubuntu/hunsu-project/src/post/post.controller.ts:87:25)
0|hunsu-project  |     at /home/ubuntu/hunsu-project/node_modules/@nestjs/core/router/router-execution-context.js:46:28
0|hunsu-project  |     at /home/ubuntu/hunsu-project/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

**Comment by KangSanLee24** [comment]
게시글 수정시에 Redis에 해쉬태그가 수정되어 저장되나요?

**Comment by KangSanLee24** [comment]
게시글 삭제시 게시글 목록 조회 Redis 비우는 기능 추가.
