### ISSUE TITLE
[BUGFIX][BACK]게시글 삭제

### ISSUE THREAD

**Issue by KangSanLee24** [KangSanLee24/hunsu-project#295]
# Issue: 🐵BUGFIX

## 🎈Description

1. 해당 게시글의 댓글의 좋아요, 싫어요가 있는 경우 FK 에러 발생 
```
0|hunsu-pr |     at CommentController.findAll (/home/ubuntu/hunsu-project/src/comment/comment.controller.ts:62:18)
0|hunsu-pr |     at /home/ubuntu/hunsu-project/node_modules/@nestjs/core/router/router-execution-context.js:46:28
0|hunsu-pr |     at /home/ubuntu/hunsu-project/node_modules/@nestjs/core/router/router-proxy.js:9:17
0|hunsu-pr | [Nest] 15951  - 08/19/2024, 4:51:06 AM   ERROR [ExceptionsHandler] Cannot delete or update a parent row: a foreign key constraint fails (`hunsu-project`.`comment_likes`, CONSTRAINT `FK_2073bf518ef7017ec19319a65e5` FOREIGN KEY (`comment_id`) REFERENCES `comments` (`id`))
0|hunsu-pr | QueryFailedError: Cannot delete or update a parent row: a foreign key constraint fails (`hunsu-project`.`comment_likes`, CONSTRAINT `FK_2073bf518ef7017ec19319a65e5` FOREIGN KEY (`comment_id`) REFERENCES `comments` (`id`))
0|hunsu-pr |     at Query.onResult (/home/ubuntu/hunsu-project/src/driver/mysql/MysqlQueryRunner.ts:246:33)
0|hunsu-pr |     at Query.execute (/home/ubuntu/hunsu-project/node_modules/mysql2/lib/commands/command.js:36:14)
0|hunsu-pr |     at PoolConnection.handlePacket (/home/ubuntu/hunsu-project/node_modules/mysql2/lib/connection.js:481:34)
0|hunsu-pr |     at PacketParser.onPacket (/home/ubuntu/hunsu-project/node_modules/mysql2/lib/connection.js:97:12)
0|hunsu-pr |     at PacketParser.executeStart (/home/ubuntu/hunsu-project/node_modules/mysql2/lib/packet_parser.js:75:16)
0|hunsu-pr |     at Socket.<anonymous> (/home/ubuntu/hunsu-project/node_modules/mysql2/lib/connection.js:104:25)
0|hunsu-pr |     at Socket.emit (node:events:519:28)
0|hunsu-pr |     at addChunk (node:internal/streams/readable:559:12)
0|hunsu-pr |     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
0|hunsu-pr |     at Socket.Readable.push (node:internal/streams/readable:390:5)

```

2. 게시글 목록 조회시 탈퇴한 회원이 있는 경우 nickname을 불러오지 못해서 목록 조회가 안되는 오류

```
0|hunsu-project  | TypeError: Cannot read properties of null (reading 'nickname')
0|hunsu-project  |     at /home/ubuntu/hunsu-project/src/post/post.service.ts:198:31
0|hunsu-project  |     at Array.map (<anonymous>)
0|hunsu-project  |     at PostService.findAll (/home/ubuntu/hunsu-project/src/post/post.service.ts:195:22)
0|hunsu-project  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
0|hunsu-project  |     at PostController.findAll (/home/ubuntu/hunsu-project/src/post/post.controller.ts:87:25)
0|hunsu-project  |     at /home/ubuntu/hunsu-project/node_modules/@nestjs/core/router/router-execution-context.js:46:28
0|hunsu-project  |     at /home/ubuntu/hunsu-project/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

`post.service.ts`에 198 line  `nickname: post?.user?.nickname,`로 수정

3. 탈퇴한 유저의 게시글에 들어갔을 때, 댓글을 불러오지 못하는 현상. 

## 🎹Progress

- [x] post.service.ts : relation을 걸지 않으면 post와 연관된 테이블을 못 지움. relation 추가
- [x] post.entity.ts
- [x] post-likes.entity.ts
- [x] post-dislikes.entity.ts
- [x] comments.entity.ts
- [x] comment-likes.entity.ts
- [x] comment-dislikes.entity.ts 에 `onDelete: 'CASCADE' 추가`

- [x] post.service.ts에 198 line  `nickname: post?.user?.nickname,`로 수정

**Comment by KangSanLee24** [comment]
post.entity / post-likes.entity / post-dislikes.entity 에 `ondeleted : cascade` 추가

comments.entity / comment-likes.entity / comment-dislikes.entity에 `ondeleted : cascade`추가

게시글을 삭제할 때, 게시글 좋아요, 싫어요 댓글을 가져오게 relations을 추가했다.
