### ISSUE TITLE
[BUGFIX][BACK]댓글

### ISSUE THREAD

**Issue by KangSanLee24** [KangSanLee24/hunsu-project#299]
# Issue: 🐵BUGFIX

## 🎈Description

#295 의 3
탈퇴한 유저의 게시글에 들어갔을 때, 댓글을 불러오지 못하는 현상.

+ 탈퇴한 유저의 댓글, 대댓글을 불러오지 못하는 현상

``` bash
0|hunsu-project  | [Nest] 15951  - 08/19/2024, 6:58:47 AM   ERROR [ExceptionsHandler] Cannot read properties of null (reading 'nickname')
0|hunsu-project  | TypeError: Cannot read properties of null (reading 'nickname')
0|hunsu-project  |     at /home/ubuntu/hunsu-project/src/comment/comment.service.ts:136:32
0|hunsu-project  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
0|hunsu-project  |     at async Promise.all (index 0)
0|hunsu-project  |     at CommentService.findCommentsById (/home/ubuntu/hunsu-project/src/comment/comment.service.ts:122:39)
0|hunsu-project  |     at CommentController.findAll (/home/ubuntu/hunsu-project/src/comment/comment.controller.ts:62:18)
0|hunsu-project  |     at /home/ubuntu/hunsu-project/node_modules/@nestjs/core/router/router-execution-context.js:46:28
0|hunsu-project  |     at /home/ubuntu/hunsu-project/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

## 🎹Progress

- [x] ToDo

**Comment by KangSanLee24** [comment]
회원탈퇴할시 localStrage에 저장되어있는 `accessToken`, `refreshToken` 비워줘야할듯

**Comment by KangSanLee24** [comment]
softDelete되서 relation을 걸어도 못 가져오는듯.

프론트에서 nickname이 undefine인 경우 탈퇴한 회원으로 표시되게 하면 되나?
